export const PRICING_OPTIONS = [
  "Freemium",
  "Free trial",
  "Free",
  "Subscription",
  "Single purchase",
  "Enterprise licensing",
  "Usage based",
];

export const AI_MODELS = [
  { id: "anthropic/claude-3.5-haiku", name: "Claude 3.5 Haiku" },
  { id: "anthropic/claude-sonnet-4", name: "Claude 4 Sonnet" },
  { id: "anthropic/claude-opus-4.1", name: "Claude Opus 4.1" },
  { id: "openai/gpt-4o", name: "OpenAI GPT-4o" },
  { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
  { id: "openai/gpt-4.1-mini", name: "GPT 4.1 mini" },
  { id: "openai/gpt-oss-120b", name: "GPT oss" },
  { id: "openai/gpt-4.1-nano", name: "GPT 4.1 nano" },
  { id: "openai/gpt-5", name: "GPT 5" },
  { id: "openai/gpt-5-nano", name: "GPT 5 nano" },
  { id: "openai/gpt-5-mini", name: "GPT 5 mini" },
];

export const quickTools = [
  {
    id: "blog",
    name: "Blog Post Outline Generator",
    memo: "This will get you started with an outline for a blog post topic. The rest is on you.",
  },
  {
    id: "headline",
    name: "Headline Rewriter",
    memo: "Need help with your headline? This will give you 5 variations.",
  },
  {
    id: "tweet",
    name: "Tweet Expander",
    memo: "Pass in twitter topic and expand it into 5-8 posts.",
  },
  {
    id: "tagline",
    name: "Tagline Generator",
    memo: "Have an idea?  Need a tagline? This will give you 5.",
  },
  {
    id: "image",
    name: "Image Prompt Generator",
    memo: "Your content needs images. This generates prompt ready image descriptions from text or a URL.",
  },
  {
    id: "quote",
    name: "Quote Generator",
    memo: "Found something quote-worthy? This will generate quotes from text a URL.",
  },
];

// A derived array of just the model IDs for efficient API validation.
export const ALLOWED_MODELS = AI_MODELS.map((model) => model.id);

export const TOOL_TAGS = [
  "3d",
  "art",
  "audio-editing",
  "accounting",
  "academic",
  "ad-creation",
  "ad-marketing",
  "agent",
  "analytics",
  "animation",
  "answers",
  "api",
  "app-builder",
  "app-development",
  "app-integration",
  "application-security",
  "appraisal",
  "architecture",
  "art-generation",
  "asset-tracking",
  "assistant",
  "attestation",
  "audience-growth",
  "audit",
  "automation",
  "avatars",
  "code-assistant",
  "autopilot",
  "avatar-generation",
  "biotechnology",
  "billing",
  "blogging",
  "board-games",
  "bookkeeping",
  "brain-imaging",
  "brainwave",
  "branding",
  "browser-extension",
  "budgeting",
  "business-intelligence",
  "business-listings",
  "business-tools",
  "calendar",
  "call-tracking",
  "case-law",
  "case-management",
  "chatbot",
  "ci/cd",
  "citations",
  "cli",
  "client-portal",
  "cloud-native",
  "cloud-storage",
  "cold-outreach",
  "collaboration",
  "color-palette",
  "compliance",
  "computational-intelligence",
  "computer-vision",
  "construction",
  "consumer-rights",
  "content-creation",
  "customer-support",
  "content-marketing",
  "content-optimization",
  "content-strategy",
  "conversation-intelligence",
  "conversational-ai",
  "copilot",
  "copywriting",
  "creative",
  "creative-suite",
  "creativity",
  "crm",
  "customer-experience",
  "customer-service",
  "cyber-security",
  "dashboard",
  "data-analysis",
  "design-assistant",
  "developer-tools",
  "data-enrichment",
  "data-extraction",
  "data-management",
  "data-science",
  "data-transformation",
  "data-visualization",
  "debugging",
  "deep-learning",
  "demo-automation",
  "developer-tool",
  "devops",
  "devsecops",
  "digital-marketing",
  "digital-therapist",
  "dispute-resolution",
  "distraction-blocker",
  "document-ai",
  "document-analysis",
  "document-automation",
  "document-processing",
  "documentation",
  "drag-and-drop",
  "editing",
  "education",
  "email-assistant",
  "efficiency",
  "email",
  "email-marketing",
  "endpoint-protection",
  "engineering",
  "erp",
  "etl",
  "exam",
  "expenses",
  "finance",
  "fun",
  "gaming",
  "general-writing",
  "gift-ideas",
  "financial-management",
  "financial-research",
  "financial-services",
  "fintech",
  "firewall-management",
  "focus",
  "font-editor",
  "forecasting",
  "forms",
  "generative-ai",
  "generative-art",
  "geospatial-analytics",
  "github",
  "grammar-checker",
  "graphics",
  "guides",
  "habit-building",
  "healthcare",
  "human-resources",
  "help-desk",
  "home-design",
  "ide",
  "ide-integration",
  "identity-governance",
  "image-analysis",
  "image-editing",
  "image-generator",
  "image-recognition",
  "inbound",
  "inbox-management",
  "incident-response",
  "information-retrieval",
  "information-sharing",
  "integration",
  "interactive",
  "interior-design",
  "inventory-management",
  "investing",
  "invoicing",
  "journaling",
  "keyword-research",
  "knowledge-base",
  "knowledge-management",
  "knowledge-sharing",
  "kubernetes",
  "lab-management",
  "landing-pages",
  "language-generation",
  "legal",
  "legal-tech",
  "lending",
  "linkedin-outreach",
  "listings",
  "litigation",
  "live-chat",
  "logo-generator",
  "low-code",
  "low-code-development",
  "machine-learning",
  "maintenance",
  "management",
  "manipulation",
  "marketing",
  "marketing-automation",
  "marketing-tool",
  "mathematics",
  "medical",
  "meeting-assistant",
  "music",
  "mental-health",
  "messaging",
  "mind-mapping",
  "mockup",
  "mobile",
  "model-sharing",
  "monetization",
  "motion-graphics",
  "network-security",
  "neural-networks",
  "newsletter",
  "nlg",
  "nlp",
  "no-code",
  "note-taking",
  "notes",
  "organization",
  "outreach",
  "pair-programming",
  "paraphraser",
  "personalization",
  "parser",
  "patch-management",
  "pdf",
  "performance-optimization",
  "personal-growth",
  "personal-wiki",
  "photo-editing",
  "photo-management",
  "phishing",
  "plagiarism-checker",
  "podcast",
  "portfolio",
  "presentation-generator",
  "presentation",
  "privacy",
  "process-optimization",
  "productivity",
  "programming",
  "project-management",
  "prompt-guides",
  "prospecting",
  "prototyping",
  "publishing",
  "python",
  "qa",
  "quant",
  "question-answering",
  "quiz",
  "real-estate",
  "recreation",
  "regression-testing",
  "regulatory",
  "repair",
  "research",
  "responsive-design",
  "risk-management",
  "rpa",
  "runtime-security",
  "sales",
  "sales-automation",
  "sales-coaching",
  "sales-engagement",
  "sales-intelligence",
  "sast",
  "scheduling",
  "science",
  "screenshare",
  "scribe",
  "search",
  "security",
  "seo",
  "serp-analysis",
  "short-form-video",
  "slideshow",
  "small-business",
  "social-media",
  "speech-to-text",
  "social-media-monitoring",
  "sound",
  "speech-analytics",
  "speech-recognition",
  "spreadsheets",
  "story-teller",
  "stable-diffusion",
  "story-generator",
  "summarizer",
  "summarization",
  "supply-chain",
  "support",
  "surveys",
  "synthetic-media",
  "task-management",
  "team-management",
  "telehealth",
  "templates",
  "testing",
  "text-editor",
  "text-generation",
  "text-to-speech",
  "text-to-video",
  "threat-detection",
  "threat-intelligence",
  "time-blocking",
  "time-management",
  "transcriber",
  "travel",
  "transcription",
  "typing",
  "typography",
  "ugc",
  "url-converter",
  "user-experience",
  "virtual-assistant",
  "virtual-reality",
  "video-editing",
  "video-generator",
  "visualization",
  "voice-ai",
  "voice-modulation",
  "voice-to-text",
  "vulnerability-management",
  "web-design",
  "web-development",
  "website-builder",
  "wellness",
  "whiteboard",
  "wiki",
  "workflow",
  "workflow-automation",
  "writing",
  "writing-assistant",
];
